spring:
  application:
    name: management-node
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8443/realms/management-node
          jwk-set-uri: https://localhost:8443/realms/management-node/protocol/openid-connect/certs
          audiences: management-node
          authorities-claim-name: resource_access
        opaquetoken:
          introspection-uri: https://localhost:8443/realms/management-node/protocol/openid-connect/token/introspect
          client-secret: 0T5S4wNAPaaOUzFVFQyenorSEC6zxcb0
          client-id: ztf-client
  flyway:
    create-schemas: on
    default-schema: mn
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: keycloak_db_user
    password: keycloak_db_user_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        default_schema: mn

# Server configuration
server:
  port: 8090
  ssl:
    key-alias: localhost
    key-store: /home/developer/Downloads/managementNode/docker/keystore.jks
    key-store-type: JKS
    key-store-password: changeit
    trust-store: /home/developer/Downloads/managementNode/docker/truststore.jks
    trust-store-password: changeit
    trust-store-type: JKS

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    uk.gov.dbt.ndtp.ia.node.management: DEBUG
