spring:
  application:
    name: management-node
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8443/realms/mng-node
          jwk-set-uri: https://localhost:8443/realms/mng-node/protocol/openid-connect/certs
          audiences: management-node
        opaquetoken:
          introspection-uri: https://localhost:8443/realms/mng-node/protocol/openid-connect/token/introspect
          client-id: management-node
          client-secret:
  flyway:
    create-schemas: on
    default-schema: mn
    locations: classpath:db/migration,classpath:db/samples # samples are only for local development
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5433/keycloak_db # this is setup to get you going easily using the Keycloak postgres so change this !
    username: ${POSTGRES_USER:keycloak_db_user}
    password: ${POSTGRES_PASSWORD:}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        default_schema: mn

# Server configuration
server:
  port: 8090
  ssl:
    key-alias: localhost
    key-store: keystore.jks #path to ssl keystore
    key-store-type: PKCS12
    key-store-password: ${CERTPASSWORD:} #keystore password
    trust-store: truststore.jks #path to ssl truststore
    trust-store-password: ${CERTPASSWORD:} #truststore password
    trust-store-type: PKCS12
    client-auth: need
    enabled: true # disable for local development Only
application:
  client:
    key-store: keystore.jks # path to MTLS client keystore
    key-store-password: ${CERTPASSWORD:} # MTLS client keystore password
    keyStoreType: JKS

# Actuator Configuration
management:
  server:
    port: 8081
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    uk.gov.dbt.ndtp.ia.node.management: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{clientId}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{clientId}] - %msg%n"
