
#
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally
# attributed to the Department for Business and Trade (UK) as the governing entity.
#

# Build stage
ARG JAR_FILE=management-node-1.0.1.jar
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
ARG JAR_FILE
WORKDIR /build

# Copy the project files
COPY pom.xml .
COPY src ./src

# Build the application
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:23-jdk-alpine
ARG JAR_FILE

WORKDIR /app

# Create directory for certificates
RUN mkdir -p /app/docker

# Copy application jar from build stage and certificates
COPY --from=build /build/target/${JAR_FILE} /app/app.jar
COPY docker/keystore.jks /app/docker/keystore.jks
COPY docker/truststore.jks /app/docker/truststore.jks

EXPOSE 8443

ENTRYPOINT ["java", "-jar", "/app/app.jar"]