/*
 * SPDX-License-Identifier: Apache-2.0
 * © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally
 * attributed to the Department for Business and Trade (UK) as the governing entity.
 */

-- Create product_type table with autogenerated primary key, name, and description (max 255)
create table if not exists product_type
(
    id          bigserial
        constraint pk_product_type
            primary key,
    name        varchar(150) not null,
    description varchar(255)
);

-- Add foreign key column to product referencing product_type(id)
alter table product add column if not exists product_type_id bigint;

alter table product
    add constraint fk_product__product_type_id
        foreign key (product_type_id) references product_type (id);

-- Optional but recommended: index for faster lookups on FK
create index if not exists idx_product__product_type_id on product (product_type_id);


-- Add default values for product_type
INSERT INTO  product_type (name, description) VALUES ('topic', 'data exchange using kafka topics');
INSERT INTO  product_type (name, description) VALUES ('file', 'file exchange using cloud file storage');

---- update all existing products to use topic product type
UPDATE product set product_type_id = (select id from product_type where name = 'topic') where product_type_id is null;

